# Generated by Django 2.0.2 on 2018-03-18 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=225)),
                ('street', models.CharField(max_length=225)),
                ('erf', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField(max_length=225)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver Restriction',
                'verbose_name_plural': 'Driver Restrictions',
            },
        ),
        migrations.CreateModel(
            name='EyesColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eye Color',
                'verbose_name_plural': 'Eyes Color',
            },
        ),
        migrations.CreateModel(
            name='HairColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hair Color',
                'verbose_name_plural': 'Hair Color',
            },
        ),
        migrations.CreateModel(
            name='LicCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('dateCreated', models.DateTimeField(verbose_name='date Created')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LicenceCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=225)),
                ('description', models.TextField(blank=True, max_length=225, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Licence Code',
                'verbose_name_plural': 'Licence Codes',
            },
        ),
        migrations.CreateModel(
            name='LicenceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenceNumber', models.CharField(max_length=225)),
                ('licenceBarcode', models.CharField(max_length=100)),
                ('idNumber', models.IntegerField()),
                ('owner', models.IntegerField()),
                ('issuedBy', models.CharField(max_length=225)),
                ('validityStart', models.DateField()),
                ('validityEnd', models.DateField()),
                ('firstIssue', models.DateField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('driverRestriction', models.ManyToManyField(to='ets.DriverRestriction')),
                ('licenceCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ets.LicenceCode')),
            ],
            options={
                'verbose_name': 'Licence Information',
                'verbose_name_plural': 'Licence Information',
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField(max_length=225)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchNumber', models.CharField(max_length=225)),
                ('assignedDevice', models.CharField(max_length=225)),
                ('dateCreated', models.DateTimeField(verbose_name='data created')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfficerTickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, default='static/30x30.png', null=True, upload_to='static/photos/%Y/%m/%d/')),
                ('idNumber', models.IntegerField(blank=True, null=True)),
                ('cellNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('town', models.CharField(blank=True, default='', max_length=100)),
                ('organization', models.CharField(blank=True, default='', max_length=100)),
                ('email_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Restrictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('dateCreated', models.DateTimeField(verbose_name='date Created')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Severity',
                'verbose_name_plural': 'Severities',
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sex',
                'verbose_name_plural': 'Sex',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellNumber', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254)),
                ('idNumber', models.IntegerField(blank=True, null=True)),
                ('vinNumber', models.CharField(blank=True, max_length=225, null=True)),
                ('regNumber', models.CharField(blank=True, max_length=225, null=True)),
                ('licenceBarcode', models.CharField(blank=True, max_length=100, null=True)),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('locationLat', models.FloatField(blank=True, null=True)),
                ('locationLog', models.FloatField(blank=True, null=True)),
                ('locationAlt', models.FloatField(blank=True, null=True)),
                ('direction', models.CharField(blank=True, max_length=100, null=True)),
                ('violationCode', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=225, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('evidencePic', models.FileField(blank=True, null=True, upload_to='')),
                ('officerBatch', models.CharField(blank=True, max_length=225, null=True)),
                ('signature', models.FileField(blank=True, null=True, upload_to='')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField(default=ets.models.get_deadline)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ets.Sex')),
            ],
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField(blank=True, max_length=225, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket Category',
                'verbose_name_plural': 'Ticket Categories',
            },
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regNumber', models.CharField(max_length=225)),
                ('vinNumber', models.CharField(max_length=225)),
                ('regBarcode', models.CharField(max_length=100)),
                ('owner', models.IntegerField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle Information',
                'verbose_name_plural': 'Vehicles Information',
            },
        ),
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle Make',
                'verbose_name_plural': 'Vehicle Make',
            },
        ),
        migrations.CreateModel(
            name='VehRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField(max_length=225)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle Restriction',
                'verbose_name_plural': 'Vehicle Restrictions',
            },
        ),
        migrations.CreateModel(
            name='ViolationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=225)),
                ('amount', models.FloatField()),
                ('description', models.TextField(max_length=225)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticketCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ets.TicketCategory')),
            ],
            options={
                'verbose_name': 'Violation Code',
                'verbose_name_plural': 'Violation Codes',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticketCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ets.TicketCategory'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ets.Sex'),
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ets.Occupation'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='licenceinfo',
            name='vehRestriction',
            field=models.ManyToManyField(to='ets.VehRestriction'),
        ),
    ]
