# Generated by Django 2.0.2 on 2018-03-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenceinfo',
            name='idNumber',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='idNumber',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='idNumber',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinfo',
            name='owner',
            field=models.CharField(max_length=12),
        ),
    ]
