# Generated by Django 2.0.2 on 2018-03-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ets', '0002_auto_20180320_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenceinfo',
            name='owner',
            field=models.CharField(max_length=12),
        ),
    ]
